//подключение моей хуйни
#include "code\modules\crafting\random_items.dm"
#include "code\modules\random_item\borg_hand.dm"
#include "code\modules\random_item\dynamo_machine.dm"
#include "code\modules\random_item\hand-made_drone.dm"
#include "code\modules\random_item\implant.dm"
#include "code\modules\random_item\lockermech.dm"
#include "code\modules\random_item\makeshift_tool.dm"
#include "code\modules\random_item\material_item.dm"
#include "code\modules\random_item\random_nodes.dm"
#include "code\modules\random_item\spot.dm"
#include "code\modules\random_item\stock_parts.dm"
#include "code\modules\random_item\quirk\quirk_all.dm"
#include "code\modules\scrap\scrap_beacon.dm"
#include "code\modules\scrap\scrap_loot.dm"
#include "code\modules\scrap\scrap_pile.dm"
#include "code\modules\scrap\slime_extract_list.dm"
